export { MovieDetailSkeleton } from "./movie-detail-skeleton";
export { MovieDetailNotFound } from "./movie-detail-not-found";
export { MovieDetailHero } from "./movie-detail-hero";
export { MovieDetailHeader } from "./movie-detail-header";
export { MovieDetailPoster } from "./movie-detail-poster";
export { MovieDetailMeta } from "./movie-detail-meta";
export { MovieDetailSidebar } from "./movie-detail-sidebar";
export { MovieDetailActions, MovieDetailWatchButton } from "./movie-detail-actions";
export { MovieDetailRelated } from "./movie-detail-related";
export { MovieDetailTabs } from "./movie-detail-tabs";
